name: Simple CI Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
      uses: actions/checkout@v3

      - name: Проверка содержимого
        run: |
          echo "Проверяем код..."
          ls -la
          echo "CI успешно выполнен!"
      - name: Проверка HTML-файла
        run: test -f index.html && echo "Файл найден!"|| echo "HTML НЕ найден!"

