name: Simple CI Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Загрузка кода
        uses: actions/checkout@v3

      - name: Проверка содержимого
        run: |
          echo "Проверяем код..."
          ls -la
          echo "CI успешно выполнен!"
      - name: Проверка HTML-файла
       Run test -f index.html && echo "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$HTML найден!" || echo "HTML НЕ найден!$$$$$$$$$$$$$$$$$$$$$$$$$$$$"



      - name: Установка HTML Validator
        run: npm install -g html-validator-cli
    
      - name: Проверка HTML на ошибки
        run: html-validator --file index.html --verbose


