name: Simple CI Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code loaded
        uses: actions/checkout@v3

      - name: Check check
        run: |
          echo "code checking..."
          ls -la
          echo "CI suckcess!"

      - name: Проверка HTML-файла
        run: test -f index.html && echo "file finded!"|| echo "HTML not finded!"


